mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')),
    path('polls/', include('polls.urls')),
    path("admin/", admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('create/', views.create, name='create'),
    path('user/<int:by_id>', views.user, name='user'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('comment/<int:id>', views.comment, name='comment'),
    path('get_captcha', views.get_captcha, name='get_captcha')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=255)
    email = models.EmailField()
    level = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    desc = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)

    class Make:
        db_table = 'posts_user'

    def __str__(self):
        return self.username


class Categories(models.Model):
    name = models.CharField(max_length=255, unique=True)
    desc = models.CharField(max_length=255)

    class Make:
        db_table = 'posts_categories'

    def __str__(self):
        return self.name


class Topics(models.Model):
    subject = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    cat = models.ForeignKey(Categories, on_delete=models.CASCADE)
    by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Make:
        db_table = 'posts_topics'

    def __str__(self):
        return self.subject


class Posts(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    topic = models.ForeignKey(Topics, on_delete=models.CASCADE)
    by = models.ForeignKey(User, on_delete=models.CASCADE)


class Comments(models.Model):
    content = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    create_user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)

posts/forms.py
from django import forms

from .models import Comments, User


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['content', 'create_user', 'post']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['create_user'].required = False
        self.fields['post'].required = False


class UserForm(forms.ModelForm):
    username = forms.CharField()
    password = forms.CharField()
    email = forms.EmailField(required=False)
    desc = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'avatar', 'desc']

posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse

from .models import User, Posts, Topics, Comments

from .forms import CommentForm, UserForm

from .utils import get_sha256_hash, gen_random_code
from .Captcha import Captcha


def index(request):
    posts = Posts.objects.select_related('by', 'topic').all().order_by('-date')
    return render(request, 'posts/index.html', {'posts': posts})


def login(request):
    username = request.POST.get('username', None)
    password = request.POST.get('password', None)
    if username and password:
        has_user = User.objects.filter(username=username).first()
        has_pass = get_sha256_hash(password) == has_user.password

        if request.session['captcha'].lower() != request.POST.get('captcha').lower():
            return render(request, 'posts/login.html', )

        if has_pass:
            request.session['userid'] = has_user.id
            request.session['username'] = has_user.username
            request.session['avatar'] = has_user.avatar.url
            return redirect('/')

    return render(request, 'posts/login.html', )


def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.password = get_sha256_hash(form.cleaned_data['password'])
            if 'avatar' in request.FILES:
                f.avatar = request.FILES['avatar']
            f.save()
            return redirect('/login')
        else:
            print(form.errors)
    return render(request, 'posts/register.html',)


def create(request):
    if request.method == 'POST':
        title = request.POST.get('title', None)
        content = request.POST.get('content', None)
        topic = Topics.objects.filter(id=request.POST.get('topic')).first()
        by = User.objects.filter(id=request.session['userid']).first()
        Posts.objects.create(title=title, content=content, topic=topic, by=by)
        return redirect('/')

    topics = Topics.objects.all()
    return render(request, 'posts/create.html', {'topics': topics})


def user(request, by_id):
    posts = Posts.objects.filter(by=by_id).order_by('-date')
    return render(request, 'posts/user.html', {'posts': posts})


def detail(request, id):
    post = Posts.objects.select_related('topic').filter(id=id).first()
    comments = Comments.objects.filter(post=id).order_by('-date')
    return render(request, 'posts/detail.html', {'post': post, 'comments': comments})


def comment(request, id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.create_user = User.objects.get(id=request.session['userid'])
            f.post_id = id
            f.save()
        else:
            print(form.errors)
    return redirect(reverse('posts:detail', args=[id]))


def get_captcha(request):
    """验证码"""
    captcha_text = gen_random_code()
    request.session['captcha'] = captcha_text
    image_data = Captcha.instance().generate(captcha_text)
    return HttpResponse(image_data, content_type='image/png')

posts/templates/posts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block header %}{% endblock %}

<div class="container-xxl">
    {% block content %}{% endblock %}

</div>

<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

posts/templates/posts/create.html
{% extends './base.html' %}

{% block title %}
    create
{% endblock %}

{% block content %}
    <form class="row g-3" action="/create/" method="post">
        {% csrf_token %}
        <div class="col-12">
            <label for="title" class="form-label">Title</label>
            <input name="title" type="text" class="form-control" id="title" placeholder="title">
        </div>

        <div class="col-md-12">
            <label for="content" class="form-label">Content</label>
            <textarea name="content" class="form-control" id="content" placeholder="content"></textarea>
        </div>

        <div class="col-md-4">
            <label for="topic" class="form-label">Topic</label>
            <select name="topic" id="topic" class="form-select">
                <option selected>Choose...</option>
                {% for topic in topics %}
                    <option value="{{ topic.id }}">{{ topic.subject }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="col-12">
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
    </form>

{% endblock %}

posts/templates/posts/detail.html
{% extends './base.html' %}

{% block title %}
    detail
{% endblock %}

{% block header %}
    {% include './header.html' %}
{% endblock %}

{% block content %}
    <br>
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between border-bottom border-success pb-2 mb-2">
                <h5>{{ post.title }}</h5>
                <div class="text-bg-warning rounded-2 p-2 fs-6 text-white">{{ post.topic }}</div>
            </div>
            <div class="text-muted">{{ post.content }}</div>
        </div>
    </div>

    <br>
    <form class="row g-3" action="{% url 'posts:comment' post.id %}" method="post">
        {% csrf_token %}

        <div class="col-12">
            <textarea class="form-control" name="content" id="" cols="10" rows="2" placeholder="说点什么吧"></textarea>
        </div>

        <div class="col-12">
            <button type="submit" class="btn btn-primary">Comment</button>
        </div>
    </form>

    <br>
    <ul class="list-group">
        {% for comment in comments %}
            <li class="list-group-item">
                <div>{{ comment.content }}</div>
                <small class="text-muted">{{ comment.date }}</small>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

posts/templates/posts/header.html
<header class="header">
    <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Logo</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link disabled" aria-current="page" href="javascript:;">Topic</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>

posts/templates/posts/index.html
{% extends './base.html' %}

{% block title %}
    Blog
{% endblock %}

{% block header %}
    {% include './header.html' %}
    <br>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xxl-8">
        <main>
            {% for post in posts %}
                <a href="{% url 'posts:detail' post.id %}" class="text-decoration-none">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12">
                                    <div class="d-flex justify-content-between border-bottom border-success pb-2 mb-2">
                                        <h5>{{ post.title }}</h5>
                                        <div class="text-bg-warning rounded-2 p-2 fs-6 text-white">{{ post.topic }}</div>
                                    </div>
                                    <div class="text-dark d-inline-block text-truncate w-100">
                                        {{ post.content }}
                                    </div>
                                    <small class="text-muted">{{ post.by }}</small>
                                    <small class="text-muted">{{ post.date }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </main>
    </div>
    <div class="col-xxl-4">
        {% include './user-card.html' %}
    </div>
</div>
{% endblock %}

posts/templates/posts/login.html
{% extends './base.html' %}

{% block title %}
    login
{% endblock %}

{% block content %}
    <form class="p-4" action="/login/" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">User name</label>
            <input type="text" class="form-control" id="exampleInputEmail1" name="username">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="captcha">
            <span class="input-group-text" id="basic-addon2">
                <img src="{% url 'posts:get_captcha' %}" alt="captcha">
            </span>
        </div>
        <div>{{ request.session.captcha }}</div>
        <a href="{% url 'posts:register' %}" class="text-success">前往注册</a>
        <br>
        <br>
        <button type="submit" class="btn btn-success w-25">login</button>
    </form>
{% endblock %}

posts/templates/posts/register.html
{% extends './base.html' %}

{% block title %}
    register
{% endblock %}

{% block content %}
    <form class="row g-3" action="/register/" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="col-md-6">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="username" placeholder="username">
        </div>
        <div class="col-md-6">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="password">
        </div>
        <div class="col-12">
            <label for="email" class="form-label">Email</label>
            <input type="email" name="email" class="form-control" id="email" placeholder="email">
        </div>
        <div class="col-12">
            <label for="desc" class="form-label">Desc</label>
            <input type="text" name="desc" class="form-control" id="desc" placeholder="desc">
        </div>
        <div class="col-12">
            <input class="form-control" name="avatar" type="file" accept=".png, .jpg, .jpeg">
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-success">Confirm</button>
        </div>
    </form>
{% endblock %}

posts/templates/posts/user-card.html
<aside class="shadow-sm">
    <div class="card w-100">
        {% if request.session.userid %}
            <div class="card-body">
                <a href="{% url 'posts:user' request.session.userid %}" class="text-decoration-none">
                    <div>
                        <img src="{{ request.session.avatar }}" alt="avatar" class="w-25 rounded-5">
                    </div>
                    <h5 class="card-title">{{ request.session.username }}</h5>
                    <p class="card-text">{{ request.session.desc }}</p>
                </a>

                <a href="{% url 'posts:create' %}" class="btn btn-outline-success btn-sm w-100">发帖</a>
            </div>
        {% else %}
            <div class="card-body">
                <a href="{% url 'posts:login' %}" class="btn btn-success btn-sm mb-1 w-100">登录</a>
            </div>
        {% endif %}
    </div>
</aside>

posts/templates/posts/user.html
{% extends './base.html' %}

{% block title %}
    user
{% endblock %}

{% block header %}
    {% include './header.html' %}
{% endblock %}

{% block content %}
    <br>

    {% include './user-card.html' %}

    <br>
    <br>

    {% for post in posts %}
        <a href="{% url 'posts:detail' post.id %}" class="text-decoration-none">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <h5 class="text-body-secondary border-bottom border-success pb-1">{{ post.title }}</h5>
                            <div class="text-dark d-inline-block text-truncate w-100">
                                {{ post.content }}
                            </div>
                            <small class="text-muted">{{ post.date }}</small>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}
{% endblock %}